// Run against an isolated data directory, never the user's main var directory.
const {chromium}=require('playwright');
const fs=require('fs'),path=require('path'),assert=require('assert').strict;
const root=path.resolve(__dirname,'..'),evidence=path.join(root,'evidence');
const fixture=JSON.parse(fs.readFileSync(path.join(root,'test-runs/credentials.json'),'utf8'));
const base=process.env.TEST_URL||'http://127.0.0.1:8001';
const report={time:new Date().toISOString(),base,checks:[],errors:[],external:[],screenshots:[]};
async function check(id,fn){try{const detail=await fn();report.checks.push({id,status:'PASS',detail});console.log('PASS '+id);}catch(e){report.checks.push({id,status:'FAIL',detail:e.message});console.log('FAIL '+id+': '+e.message);}}
async function main(){
 const browser=await chromium.launch({channel:'msedge',headless:true});report.browser=browser.version();
 const context=await browser.newContext({viewport:{width:1440,height:960}}), other=await browser.newContext({viewport:{width:1280,height:900}});
 for(const c of [context,other]){await c.route('**/*',route=>{const url=route.request().url();if(!url.startsWith(base)&&!url.startsWith('data:')){report.external.push(url);return route.abort();}return route.continue();});}
 const a=await context.newPage(),b=await other.newPage();for(const p of [a,b])p.on('pageerror',e=>report.errors.push(e.message));
 async function login(page,user){await page.goto(base+'/account/login/');await page.locator('[name=username]').fill(user);await page.locator('[name=password]').fill(fixture.password);await Promise.all([page.waitForURL(base+'/'),page.getByRole('button',{name:'登录',exact:true}).click()]);}
 async function screenshot(page,name){await page.screenshot({path:path.join(evidence,name)});report.screenshots.push(name);}
 const idaes=fixture.papers.find(x=>x.profile==='idaes-pair-v1'),ammonia=fixture.papers.find(x=>x.profile==='ammonia-pair-v2');
 async function read(page,paper){await page.goto(`${base}/papers/${paper.id}/`);await page.locator('#article math').first().waitFor();await page.evaluate(()=>Promise.all([...document.querySelectorAll('#article img')].map(im=>im.complete?Promise.resolve():new Promise(r=>{im.onload=r;im.onerror=r;}))));}
 async function open(page,kind){if(kind==='settings'){await page.locator('.readerbar #theme').waitFor({state:'visible'});return;}await page.locator(`[data-panel=${kind}]`).click();await page.locator('#panel').waitFor({state:'visible'});}
 async function close(page){if(await page.locator('#panel').isVisible())await page.locator('[data-close]').click();}
 async function api(page,paper,endpoint,method='GET',data){const token=await page.locator('#reader').getAttribute('data-csrf');return page.request.fetch(`${base}/api/papers/${paper.id}/${endpoint}`,{method,headers:{'X-CSRFToken':token},...(data===undefined?{}:{data})});}
 await check('A04 A08 login and compact library',async()=>{await login(a,'reader_a');await login(b,'reader_b');assert.equal(await a.locator('.paper-row').count(),2);await screenshot(a,'library-1440.png');});
 for(const [paper,counts] of [[idaes,{pairs:234,math:145,images:19,eq:13}],[ammonia,{pairs:158,math:750,images:10,eq:70}]]){
  await check(`E02 E03 ${paper.profile} actual DOM/images/MathML`,async()=>{await read(a,paper);const actual=await a.evaluate(()=>({pairs:document.querySelectorAll('#article .pair').length,math:document.querySelectorAll('#article math').length,images:document.querySelectorAll('#article img').length,eq:document.querySelectorAll('#article .equation').length,failed:[...document.querySelectorAll('#article img')].filter(i=>!i.complete||!i.naturalWidth).length,badmath:[...document.querySelectorAll('#article math')].filter(m=>m.namespaceURI!=='http://www.w3.org/1998/Math/MathML').length}));assert.equal(actual.failed,0);assert.equal(actual.badmath,0);for(const key in counts)assert.equal(actual[key],counts[key]);return actual;});
  await check(`E01 E03 ${paper.profile} 1440/1280/390 layouts`,async()=>{for(const width of [1440,1280,390]){await a.setViewportSize({width,height:960});await a.evaluate(()=>window.scrollTo(0,0));await a.waitForTimeout(150);const layout=await a.evaluate(()=>{const p=document.querySelector('#article .pair'),en=p.querySelector('.en').getBoundingClientRect(),zh=p.querySelector('.zh').getBoundingClientRect(),bar=document.querySelector('.readerbar').getBoundingClientRect(),back=document.querySelector('.back').getBoundingClientRect();return{page:document.documentElement.scrollWidth,view:innerWidth,en:{top:en.top,bottom:en.bottom,right:en.right},zh:{top:zh.top,left:zh.left},back:back.width,bar:bar.height};});assert.ok(layout.page<=width+2,JSON.stringify(layout));assert.ok(layout.back>60);if(width===390)assert.ok(layout.zh.top>=layout.en.bottom-2);else assert.ok(layout.zh.left>layout.en.right);await screenshot(a,`${paper.profile}-${width}.png`);}await a.setViewportSize({width:1440,height:960});});
  await check(`E04 ${paper.profile} dynamic object navigation`,async()=>{await open(a,'contents');const nav=await a.locator('#article-nav').textContent();const entries=JSON.parse(nav);for(const [kind,items] of Object.entries(entries)){assert.ok(items.length>0);const last=items.at(-1);await a.evaluate(({kind})=>{const labels={sections:'章节',figures:'图片',tables:'表格',equations:'公式'};for(const d of document.querySelectorAll('#nav-list details'))if(d.querySelector('summary').textContent.startsWith(labels[kind]))d.open=true;},{kind});await a.locator(`#nav-list a[href="#${last.id}"]`).click();assert.equal(await a.locator('#panel').isVisible(),false);const top=await a.locator(`[id="${last.id}"]`).evaluate(el=>el.getBoundingClientRect().top);assert.ok(top>=0&&top<400,'navigation top '+top);await open(a,'contents');}await close(a);return Object.fromEntries(Object.entries(entries).map(([k,v])=>[k,v.length]));});
  await check(`E05 ${paper.profile} English/Chinese search preserves science`,async()=>{const before=await a.locator('#article math').evaluateAll(ms=>ms.map(m=>m.outerHTML).join(''));for(const q of ['model','模型']){await open(a,'search');await a.locator('#in-paper-search').fill(q);await a.waitForTimeout(250);assert.match(await a.locator('#search-status').textContent(),/找到 [1-9]/);await a.locator('#search-next').click();assert.equal(await a.locator('#panel').isVisible(),false);await open(a,'search');await a.locator('#search-prev').click();await open(a,'search');await a.locator('#search-clear').click();await close(a);}assert.equal(await a.locator('#article math').evaluateAll(ms=>ms.map(m=>m.outerHTML).join('')),before);});
  await check(`E06 E07 ${paper.profile} themes font sources image focus`,async()=>{await open(a,'settings');await a.locator('#theme').selectOption('dark');await a.locator('#font-size').selectOption('20');await a.locator('#source-toggle').uncheck();assert.ok(await a.locator('html').evaluate(el=>el.classList.contains('dark')));await a.keyboard.press('Escape');assert.equal(await a.locator('#panel').isVisible(),false);await screenshot(a,`${paper.profile}-dark.png`);const img=a.locator('#article img').first();await img.scrollIntoViewIfNeeded();const y=await a.evaluate(()=>scrollY);assert.equal(await img.evaluate(el=>getComputedStyle(el).filter),'none');await img.click();await a.locator('#zoom-in').click();assert.equal(await a.locator('#zoom-label').textContent(),'150%');await a.locator('#image-close').click();assert.ok(Math.abs(await a.evaluate(()=>scrollY)-y)<3);await open(a,'settings');await a.locator('#theme').selectOption('sepia');await a.locator('#theme').selectOption('auto');await a.locator('#font-size').selectOption('18');await a.locator('#source-toggle').check();await close(a);});
 }
 await read(a,idaes);await read(b,idaes);
 await check('C19 real concurrent HTTP saves',async()=>{let r=await Promise.all([api(a,idaes,'ratings/interesting/','PUT',{value:5}),api(b,idaes,'ratings/interesting/','PUT',{value:4}),api(a,idaes,'ratings/importance/','PUT',{value:3}),api(b,idaes,'ratings/importance/','PUT',{value:5})]);r.forEach(x=>assert.equal(x.status(),200));const result=await(await api(a,idaes,'ratings/')).json();assert.equal(result.interesting.average,4.5);assert.equal(result.interesting.count,2);assert.equal(result.importance.average,4);assert.equal(result.importance.count,2);return result;});
 await check('C20 UI failed request retains saved score',async()=>{await open(a,'scores');await a.locator('#rating-interesting .selected').waitFor();assert.equal(await a.locator('#rating-interesting .selected').textContent(),'5');await a.route('**/ratings/interesting/',r=>r.abort('failed'));await a.locator('#rating-interesting .rating-buttons button').nth(0).click();await a.waitForTimeout(400);assert.equal(await a.locator('#rating-interesting .selected').textContent(),'5');assert.notEqual(await a.locator('#rating-status').textContent(),'已保存');await a.unroute('**/ratings/interesting/');await screenshot(a,'rating-failure.png');await close(a);});
 await check('D02 D06 browser comments and one-level reply',async()=>{await open(a,'comments');await a.locator('#comment-body').fill('共同阅读测试：<script>window.commentExecuted=true</script>');await a.locator('#comment-form .primary').click();await a.waitForTimeout(400);const root=a.locator('.comment:not(.reply)').last();assert.match(await root.textContent(),/测试甲/);await close(a);await open(b,'comments');await b.locator('.comment:not(.reply)').last().getByRole('button',{name:'回复',exact:true}).click();await b.locator('#comment-body').fill('测试乙的一层回复。');await b.locator('#comment-form .primary').click();await b.waitForTimeout(400);assert.equal(await b.locator('.comment.reply').last().getByRole('button',{name:'回复',exact:true}).count(),0);assert.equal(await b.evaluate(()=>window.commentExecuted),undefined);await screenshot(b,'comments-two-users.png');await close(b);});
 await check('E08 account paper revision storage and explicit hash',async()=>{await a.evaluate(()=>scrollTo(0,6500));await a.waitForTimeout(500);await a.reload();await a.waitForTimeout(400);assert.ok(Math.abs(await a.evaluate(()=>scrollY)-6500)<10);await b.goto(`${base}/papers/${ammonia.id}/`);assert.equal(await b.evaluate(()=>scrollY),0);await a.goto(`${base}/papers/${idaes.id}/#p-eq-13`);await a.waitForTimeout(300);assert.ok(await a.locator('#p-eq-13').evaluate(el=>el.getBoundingClientRect().top)<300);const keys=await a.evaluate(()=>Object.keys(localStorage));assert.ok(keys.some(k=>/^paper-reader:v1:\d+:[a-f0-9-]+:[a-f0-9]{64}$/.test(k)));return{keys:keys.length,format:'v1/account/paper/contenthash'};});
 await check('B03 B14 full upload-preview-publish browser path',async()=>{await a.goto(base+'/upload/');const sample=`<!doctype html><html><body><main id="top"><header><div class="pair"><div class="en"><h2>Browser validation ${Date.now()}</h2></div><div class="zh"><h2>浏览器隔离上传验证</h2></div></div></header><section class="unit paragraph" id="example"><div class="pair"><div class="en">A complete test paragraph.</div><div class="zh">完整测试段落。</div></div></section><script>window.uploadExecuted=true;fetch('https://invalid.example/');</script><a href="java&#x73;cript:alert(1)" onclick="alert(1)">安全清理测试</a></main></body></html>`;await a.locator('[name=html]').setInputFiles({name:'bilingual.html',mimeType:'text/html',buffer:Buffer.from(sample)});await a.locator('[name=categories]').first().check();await a.getByRole('button',{name:'检查并预览 →'}).click();await a.waitForURL('**/preview/**');assert.match(await a.locator('.success').textContent(),/格式检查通过/);assert.equal(await a.evaluate(()=>window.uploadExecuted),undefined);assert.equal(await a.locator('#article script,#article [onclick]').count(),0);await a.locator('[name=confirm]').check();await a.getByRole('button',{name:'发布论文',exact:true}).click();await a.waitForURL('**/papers/**');assert.equal(await a.evaluate(()=>window.uploadExecuted),undefined);});
 await check('E09 installed core with all external destinations blocked',async()=>{await read(a,idaes);await open(a,'scores');await a.locator('#rating-importance .rating-buttons button').nth(2).click();await a.waitForTimeout(300);assert.equal(await a.locator('#rating-status').textContent(),'已保存');await close(a);assert.equal(report.external.length,0);assert.equal(report.errors.length,0);});
 await browser.close();fs.writeFileSync(path.join(evidence,'browser-results.json'),JSON.stringify(report,null,2));
 if(report.checks.some(c=>c.status==='FAIL'))process.exitCode=1;
}
main().catch(e=>{report.fatal=e.stack;fs.writeFileSync(path.join(evidence,'browser-results.json'),JSON.stringify(report,null,2));console.error(e.message);process.exitCode=1;});
