const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('assert').strict;
const root=path.resolve(__dirname,'..'),base='http://127.0.0.1:8048',out=path.join(root,'evidence/usability-v3'),f=JSON.parse(fs.readFileSync(path.join(root,'test-runs/four-views/credentials.json'),'utf8'));
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true}),p=await b.newPage({viewport:{width:1366,height:768}}),report={checks:[]};async function check(id,fn){try{await fn();report.checks.push({id,status:'PASS'});console.log('PASS '+id);}catch(e){report.checks.push({id,status:'FAIL',detail:e.message});console.log('FAIL '+id+' '+e.message);}}async function read(paper,view='zh'){await p.goto(`${base}/papers/${paper.id}/?view=${view}`);await p.evaluate(()=>GAReader.ready);await p.waitForTimeout(200);}async function choose(rid){await p.evaluate(rid=>{const el=document.querySelector(`[data-representation="${rid}"]`),map=GAReaderText.logical(el),r=GAReaderText.restore(map,0,Math.min(14,map.chars.length));const rect=r.getBoundingClientRect();scrollTo(0,scrollY+rect.top-document.querySelector('.readerbar').offsetHeight-55);getSelection().removeAllRanges();getSelection().addRange(r);},rid);await p.waitForTimeout(250);await p.evaluate(()=>document.dispatchEvent(new Event('selectionchange')));await p.locator('#selection-tools').waitFor({state:'visible'});}
await require('./usability-guard.cjs')(p,base,'restored-verified');await p.goto(base+'/login/');await p.locator('[name=username]').fill('reader_a');await p.locator('[name=password]').fill(f.password);await Promise.all([p.waitForURL(base+'/'),p.getByRole('button',{name:'登录',exact:true}).click()]);const idaes=f.papers.find(p=>p.profile==='idaes-pair-v1'),ammonia=f.papers.find(p=>p.profile==='ammonia-pair-v2');
await check('A3 A6 create directly from open overview; preserve other paper draft',async()=>{
 await read(ammonia);const rid=await p.locator('[data-representation][data-rep-language=zh]').first().getAttribute('data-representation');await choose(rid);await p.locator('#selection-annotate').click();await p.locator('#annotation-body').fill('另一篇论文的未完成草稿');const key=await p.evaluate(()=>GAReaderComposer.editor.key);await p.locator('#composer-close').click();await read(idaes);await p.locator('#annotations-toggle').click();assert.equal(await p.locator('#annotation-overview').isVisible(),true);await choose('p-u001::zh::0');await p.locator('#selection-annotate').click();await p.locator('#annotation-body').fill('从汇总回到正文新建');assert.equal(await p.locator('#annotation-overview').isVisible(),false);assert.equal(await p.locator('#annotation-composer .annotation-card').count(),0);await p.locator('#annotation-discard').click();await p.locator('#discard-yes').click();assert.equal(await p.evaluate(k=>JSON.parse(localStorage.getItem(k)).body,key),'另一篇论文的未完成草稿');
});
await check('B4 actual image reload, reply expansion, scroll and resize real SVG endpoint',async()=>{
 await p.locator('#inline-toggle').evaluate(el=>{if(el.getAttribute('aria-pressed')==='false')el.click();});await p.evaluate(async()=>{const note=[...GAReaderAnnotations.notes.values()].find(n=>n.source?.segments[0]?.unit_id==='p-u001'&&n.projections.some(p=>p.precision==='exact'));window.layoutNote=note.id;await GAReaderAnnotations.locate(note);});
 for(const width of [1366,1440,1920]){await p.setViewportSize({width,height:900});await p.evaluate(async()=>{const img=document.querySelector('#article img');await new Promise(resolve=>{img.onload=resolve;img.onerror=resolve;img.src=new URL(img.src).pathname+'?verify='+Date.now();});const card=document.querySelector(`.annotation-card[data-thread="${window.layoutNote}"]`);if(card?.querySelector('.annotation-replies'))card.querySelector('.annotation-replies').open=true;scrollBy(0,20);});await p.waitForTimeout(300);const delta=await p.evaluate(()=>{GAReaderAnnotations.paintGeometry();const note=GAReaderAnnotations.notes.get(window.layoutNote),r=note.projections.filter(p=>p.precision==='exact').flatMap(GAReaderGeometry.rectsFor).filter(r=>r.bottom>document.querySelector('.readerbar').offsetHeight&&r.top<innerHeight).at(-1),line=document.querySelector(`#annotation-connectors path[data-thread="${window.layoutNote}"]`);return {found:!!line&&!!r,error:line&&r?Math.abs(+line.dataset.sourceX-r.right)+Math.abs(+line.dataset.sourceY-r.bottom-2):999};});assert.ok(delta.found&&delta.error<3,JSON.stringify(delta));}
});
await check('E4 E6 PDF at all required viewports and themes, no horizontal page overflow',async()=>{let cases=0;for(const paper of [idaes,ammonia]){await read(paper,'pdf');await p.evaluate(()=>GAReaderPDF.load());for(const [width,height] of [[1366,768],[1440,900],[1920,1080],[390,844]]){await p.setViewportSize({width,height});for(const theme of ['light','dark']){await p.locator('#theme').selectOption(theme);await p.locator('#pdf-fit-width').click();await p.evaluate(()=>GAReaderPDF.jump(0));await p.waitForTimeout(200);const m=await p.evaluate(()=>({w:innerWidth,sw:document.documentElement.scrollWidth,canvas:!!document.querySelector('#pdf-reader canvas')}));assert.ok(m.canvas&&m.sw<=m.w+2,JSON.stringify(m));cases++;}}}report.pdfViewportCases=cases;});
await b.close();fs.writeFileSync(path.join(out,'layout-followup-results.json'),JSON.stringify(report,null,2));if(report.checks.some(r=>r.status==='FAIL'))process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1;});
