const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),out=path.join(root,'evidence/usability-v3'),base='http://127.0.0.1:8047',f=JSON.parse(fs.readFileSync(path.join(root,'test-runs/four-views/credentials.json'),'utf8'));
const report={checks:[],errors:[]};let b,ca,cb,a,p;
async function check(id,fn){try{const detail=await fn();report.checks.push({id,status:'PASS',detail});console.log('PASS '+id);}catch(e){report.checks.push({id,status:'FAIL',detail:e.message});console.log('FAIL '+id+' '+e.message);}fs.writeFileSync(path.join(out,'library-results.json'),JSON.stringify(report,null,2));}
async function login(p,user){await p.goto(base+'/login/');await p.locator('[name=username]').fill(user);await p.locator('[name=password]').fill(f.password);await Promise.all([p.waitForURL(base+'/'),p.getByRole('button',{name:'登录',exact:true}).click()]);}
async function tagAction(name,action){await a.goto(base+'/admin/library/tag/');const row=a.locator('#result_list tbody tr').filter({has:a.getByRole('link',{name,exact:true})});await row.locator('[name=_selected_action]').check();await a.locator('select[name=action]').first().selectOption(action);await a.locator('button[name=index]').first().click();}
const paper=f.papers.find(p=>p.profile==='idaes-pair-v1');
async function api(p,endpoint,method='GET',data){const csrf=await p.locator('#reader').getAttribute('data-csrf');const r=await p.request.fetch(`${base}/api/papers/${paper.id}/${endpoint}`,{method,headers:{'X-CSRFToken':csrf},...(data===undefined?{}:{data})});return {status:r.status(),data:await r.json()};}
(async()=>{b=await chromium.launch({channel:'msedge',headless:true});ca=await b.newContext({viewport:{width:1366,height:768}});cb=await b.newContext({viewport:{width:1366,height:768}});a=await ca.newPage();p=await cb.newPage();for(const page of [a,p]){page.setDefaultTimeout(10000);page.on('pageerror',e=>report.errors.push(e.message));}const health=await(await p.request.get(base+'/healthz/')).json();assert.equal(health.instance,JSON.parse(fs.readFileSync(path.join(root,'test-runs/usability-v3/working/local.json'),'utf8')).instance_id);
await login(a,'test_manager');await login(p,'reader_b');
await check('D4 D5 controlled vocabulary, no-tag form and preview revalidation without reupload',async()=>{
 await a.goto(base+'/admin/library/tag/');await a.locator('#action-toggle').check();await a.locator('select[name=action]').first().selectOption('enable');await a.locator('button[name=index]').first().click();
 await p.goto(base+'/upload/');const audit=JSON.parse(fs.readFileSync(path.join(root,'reference_audit.json'),'utf8')),ref=audit.papers.find(r=>r.paper_key==='idaes'),html=fs.readFileSync(path.join(root,ref.html),'utf8')+'\n<!-- isolated v3 publish '+Date.now()+' -->';
 await p.locator('[name=html]').setInputFiles({name:'isolated-v3.html',mimeType:'text/html',buffer:Buffer.from(html)});await p.locator('[name=categories]').first().check();await p.getByRole('button',{name:'检查并预览 →'}).click();assert.match(await p.locator('[aria-label=筛选可选标签]').evaluate(el=>el.validationMessage),/至少选择1/);
 await p.locator('[aria-label=筛选可选标签]').fill('成本');await p.locator('.tag-results').getByRole('button',{name:'成本模型',exact:true}).click();await p.locator('.optional summary').click();await p.locator('[name=title_zh]').fill('v3 隔离上传验收');await p.getByRole('button',{name:'检查并预览 →'}).click();await p.waitForURL('**/preview/*/');assert.match(await p.locator('.preview-banner').textContent(),/成本模型/);global.stage=p.url();await tagAction('成本模型','disable');await p.locator('[name=confirm]').check();await p.getByRole('button',{name:'发布论文',exact:true}).click();await p.locator('.error').waitFor();assert.match(await p.locator('.error').textContent(),/分类或标签无效/);await p.getByRole('link',{name:'← 修改元信息'}).click();assert.equal(await p.locator('input[type=file]').count(),0);await p.locator('[aria-label=筛选可选标签]').fill('IDAES');await p.locator('.tag-results').getByRole('button',{name:'IDAES',exact:true}).click();await p.getByRole('button',{name:'保存并返回预览'}).click();await p.waitForURL(global.stage);assert.match(await p.locator('.preview-banner').textContent(),/IDAES/);await p.locator('[name=confirm]').check();await p.getByRole('button',{name:'发布论文',exact:true}).click();await p.waitForURL('**/papers/*/');global.newPaper=await p.locator('#reader').getAttribute('data-paper');assert.equal(await p.locator('button[data-view=pdf]').isDisabled(),true);assert.match(await p.locator('#no-pdf').textContent(),/未提供原版/);
 await a.goto(base+`/admin/library/paper/${global.newPaper}/change/`);await a.locator('[name=visible]').uncheck();await a.locator('[name=_save]').click();await tagAction('成本模型','enable');return {createdPaper:global.newPaper,noReupload:true,hiddenAfterTest:true};
});
await check('D1 D3 D7 D8 metadata labels, multi-category home, flat filters and scroll return',async()=>{
 await a.goto(`${base}/papers/${paper.id}/metadata/`);await a.locator('[aria-label=筛选可选标签]').fill('IDAES');const option=a.locator('.tag-results').getByRole('button',{name:'IDAES',exact:true});if(await option.count())await option.click();await a.getByLabel('AI',{exact:true}).check();await a.getByRole('button',{name:'保存',exact:true}).click();await a.waitForURL('**/papers/*/');
 await p.goto(base+'/');assert.equal(await p.locator('#recent .paper-row').count(),2);const nav=p.locator('.section-nav a').filter({hasText:'AI'});await nav.click();assert.ok(await p.locator('.home-section:visible').count()>=4);const tagLink=p.locator('#recent .paper-row').filter({hasText:'IDAES 过程'}).locator('.paper-meta a').filter({hasText:'IDAES'});global.tagId=new URL(await tagLink.getAttribute('href'),base).searchParams.get('tag');
 await p.goto(`${base}/?q=IDAES&tag=${global.tagId}&sort=interesting&page=1`);assert.equal(await p.locator('.paper-row').count(),1);assert.equal(await p.locator('.home-section').count(),0);await p.screenshot({path:path.join(out,'home-search-tags.png')});
 await p.setViewportSize({width:390,height:440});await p.goto(`${base}/?category=2&sort=interesting&page=1`);await p.evaluate(()=>scrollTo(0,240));await p.waitForTimeout(250);await p.locator('[data-paper-link]').first().click();await p.waitForURL('**/papers/*/');const expected=await p.evaluate(()=>{const prefix=`gareader:home:v3:${document.body.dataset.readerInstance}:${document.body.dataset.readerUser}:`,url=sessionStorage.getItem(prefix+'last');return {url,y:Number(sessionStorage.getItem(prefix+url))};});await p.locator('.reader-heading .back').click();await p.waitForURL(base+expected.url);await p.waitForTimeout(400);assert.ok(Math.abs(await p.evaluate(()=>scrollY)-expected.y)<4,JSON.stringify(expected));assert.match(p.url(),/sort=interesting/);assert.match(p.url(),/page=1/);await p.setViewportSize({width:1366,height:768});
});
await check('E1 E2 C4 remove ghosts, keep visible replies, revoke hidden quotes and preserve draft',async()=>{
 await p.goto(`${base}/papers/${paper.id}/?view=zh`);await a.goto(`${base}/papers/${paper.id}/?view=zh`);await p.waitForFunction(()=>GAReaderAnnotations?.notes.size>0);await a.waitForFunction(()=>GAReaderAnnotations?.notes.size>0);const source=await p.evaluate(()=>[...GAReaderAnnotations.notes.values()].find(n=>n.source?.source_language==='zh').source);
 const n=await api(p,'annotations/','POST',{body:'v3 visibility root',source,request_key:crypto.randomUUID()});assert.equal(n.status,201);await p.evaluate(()=>GAReaderAnnotations.refresh({full:true}));await api(p,`comments/${n.data.id}/`,'DELETE',{version:1});await p.evaluate(()=>GAReaderAnnotations.refresh());assert.equal(await p.evaluate(id=>GAReaderAnnotations.notes.has(id),n.data.id),false);
 const rootNote=await api(p,'annotations/','POST',{body:'v3 reply placeholder root',source,request_key:crypto.randomUUID()});await api(a,'comments/','POST',{body:'v3 visible reply',parent:rootNote.data.id,request_key:crypto.randomUUID()});await api(p,`comments/${rootNote.data.id}/`,'DELETE',{version:1});await p.evaluate(()=>GAReaderAnnotations.refresh({full:true}));const rootState=await p.evaluate(id=>GAReaderAnnotations.notes.get(id),rootNote.data.id);assert.equal(rootState.body,null);assert.equal(rootState.replies[0].body,'v3 visible reply');assert.ok(rootState.source);
 const hidden=await api(p,'annotations/','POST',{body:'v3 moderation source',source,request_key:crypto.randomUUID()});await api(a,'comments/','POST',{body:'v3 visible reply after moderation',parent:hidden.data.id,request_key:crypto.randomUUID()});await p.evaluate(()=>GAReaderAnnotations.refresh({full:true}));const before=await p.evaluate(id=>GAReaderAnnotations.notes.get(id),hidden.data.id);await p.evaluate(id=>{const n=GAReaderAnnotations.notes.get(id);return GAReaderComposer.open({mode:'reply',item:n,thread:n});},hidden.data.id);await p.locator('#annotation-body').fill('正在输入，隐藏后应保留的草稿');await api(a,`comments/${hidden.data.id}/hide/`,'POST',{hidden:true,version:1});await p.evaluate(()=>GAReaderAnnotations.refresh());assert.equal(await p.locator('#annotation-body').inputValue(),'正在输入，隐藏后应保留的草稿');assert.equal(await p.locator('#annotation-save').isDisabled(),true);assert.equal(await p.evaluate(()=>GAReaderComposer.editor.source),null);assert.equal((await p.request.get(base+before.source_url)).status(),404);await p.screenshot({path:path.join(out,'hidden-source-draft.png')});await p.locator('#annotation-discard').click();await p.locator('#discard-yes').click();
});
await b.close();if(report.checks.some(x=>x.status==='FAIL')||report.errors.length)process.exitCode=1;
})().catch(async e=>{console.error(e);if(b)await b.close();process.exitCode=1;});
