const {chromium}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),dir=path.join(root,'test-runs/usability-v3'),base='http://127.0.0.1:8047';
const fixture=JSON.parse(fs.readFileSync(path.join(root,'test-runs/four-views/credentials.json'),'utf8'));
const output=path.join(root,'evidence/usability-v3');fs.mkdirSync(output,{recursive:true});
const report={time:new Date().toISOString(),checks:[],errors:[],external:[],screenshots:[]};let browser,context,page,other;
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function check(id,fn){try{const detail=await fn();report.checks.push({id,status:'PASS',detail});console.log('PASS '+id);}catch(e){report.checks.push({id,status:'FAIL',detail:e.message});console.log('FAIL '+id+': '+e.message);try{await shot('failure-'+report.checks.length);}catch{}}fs.writeFileSync(path.join(output,'browser-results.json'),JSON.stringify(report,null,2));}
async function shot(name){await wait(250);await page.screenshot({path:path.join(output,name+'.png')});report.screenshots.push(name+'.png');}
async function login(p,user){await p.goto(base+'/login/');await p.locator('[name=username]').fill(user);await p.locator('[name=password]').fill(fixture.password);await Promise.all([p.waitForURL(base+'/'),p.getByRole('button',{name:'登录',exact:true}).click()]);}
const idaes=fixture.papers.find(p=>p.profile==='idaes-pair-v1'),ammonia=fixture.papers.find(p=>p.profile==='ammonia-pair-v2');
async function read(paper=idaes,view='zh'){await page.goto(`${base}/papers/${paper.id}/?view=${view}`);await page.waitForFunction(()=>window.GAReaderAnnotations?.notes.size>0);await page.evaluate(()=>GAReader.ready);await wait(180);}
async function api(endpoint,method='GET',data,p=page,paper=idaes){const csrf=await p.locator('#reader').getAttribute('data-csrf');const r=await p.request.fetch(`${base}/api/papers/${paper.id}/${endpoint}`,{method,headers:{'X-CSRFToken':csrf},...(data===undefined?{}:{data})});return {status:r.status(),data:await r.json()};}
async function select(representation='p-u001::zh::0',start=0,end=14){await page.evaluate(({representation,start,end})=>{const el=[...document.querySelectorAll('[data-representation]')].find(e=>representation?e.dataset.representation===representation:e.dataset.repLanguage==='zh'&&GAReaderText.logical(e).chars.length>80);el.scrollIntoView({block:'center',behavior:'instant'});const map=GAReaderText.logical(el),range=GAReaderText.restore(map,start,Math.min(map.chars.length,end));const r=range.getBoundingClientRect(),bar=document.querySelector('.readerbar').getBoundingClientRect().bottom;scrollTo(0,scrollY+r.top-bar-60);getSelection().removeAllRanges();getSelection().addRange(range);document.dispatchEvent(new Event('selectionchange'));},{representation,start,end});await wait(250);await page.evaluate(()=>document.dispatchEvent(new Event('selectionchange')));await page.locator('#selection-tools').waitFor({state:'visible'});}
async function newDraft(text){await select();await page.locator('#selection-annotate').click();await page.locator('#annotation-body').fill(text);}
async function main(){browser=await chromium.launch({channel:'msedge',headless:true});report.browser=browser.version();context=await browser.newContext({viewport:{width:1366,height:768}});page=await context.newPage();page.setDefaultTimeout(8000);page.on('pageerror',e=>report.errors.push(e.message));page.on('requestfailed',r=>{if(!report.failedRequests)report.failedRequests=[];report.failedRequests.push({path:new URL(r.url()).pathname,error:r.failure()?.errorText});});
 await context.route('**/*',route=>{const url=route.request().url();if(!url.startsWith(base)&&!url.startsWith('data:')&&!url.startsWith('blob:')){report.external.push(url);return route.abort();}return route.continue();});
 const health=await(await page.request.get(base+'/healthz/')).json();assert.equal(health.instance,JSON.parse(fs.readFileSync(path.join(dir,'working/local.json'),'utf8')).instance_id,'Refuse non-isolated server');
 await check('D1-D2 home expanded sections, original paper count and no tabs',async()=>{await login(page,'reader_a');assert.ok(await page.locator('.home-section').count()>=2);assert.equal(await page.locator('[role=tab]').count(),0);assert.equal(await page.locator('#recent .paper-row').count(),2);await shot('home-sections-1366');return {sections:await page.locator('.home-section').count()};});
 await check('A1 A3 compose alone preserves scroll and overview lifecycle',async()=>{await read();await page.locator('#annotations-toggle').click();assert.equal(await page.locator('#annotation-overview').isVisible(),true);await page.locator('#annotations-close').click();await select();const y=await page.evaluate(()=>scrollY);await page.locator('#selection-annotate').click();await page.locator('#annotation-body').fill('v3 隔离草稿，关闭保留');assert.equal(await page.locator('#annotation-overview').isVisible(),false);assert.equal(await page.locator('#annotation-composer .annotation-card').count(),0);assert.ok(Math.abs(await page.evaluate(()=>scrollY)-y)<3,'scroll changed after composer');await shot('compose-only');await page.evaluate(()=>GAReaderAnnotations.refresh());assert.equal(await page.locator('#annotation-overview').isVisible(),false);await page.keyboard.press('Escape');assert.equal(await page.locator('#annotation-composer').isVisible(),false);await page.locator('#continue-draft').click();assert.equal(await page.locator('#annotation-body').inputValue(),'v3 隔离草稿，关闭保留');await page.locator('#annotation-discard').click();await page.locator('#discard-yes').click();});
 await check('A2 A4 A6 isolated editor, IME, offline retry, refresh and idempotency',async()=>{
  await page.setViewportSize({width:1366,height:768});await read();await page.locator('#theme').selectOption('light');await page.locator('#font-reset').click();await newDraft('v3 草稿 · 断网后重试 '+Date.now());
  const content=await page.locator('#annotation-body').inputValue(),source=await page.evaluate(()=>GAReaderComposer.editor.source),before=(await api('annotations/')).data.count;
  await page.locator('#annotation-body').dispatchEvent('compositionstart');await page.locator('button[data-view=en]').click();assert.equal(await page.locator('#reader').getAttribute('data-view'),'zh');await page.locator('#annotation-form').dispatchEvent('submit');assert.equal((await api('annotations/')).data.count,before);await page.locator('#annotation-body').dispatchEvent('compositionend');
  await context.setOffline(true);await page.locator('#annotation-save').click();await page.waitForFunction(()=>!GAReaderComposer.busy);assert.equal(await page.locator('#annotation-body').inputValue(),content);assert.equal(await page.locator('#annotation-overview').isVisible(),false);await context.setOffline(false);
  const key=await page.evaluate(()=>GAReaderComposer.editor.request_key);await page.locator('#composer-close').click();await page.reload();await page.locator('#continue-draft').waitFor();await page.locator('#continue-draft').click();assert.equal(await page.locator('#annotation-body').inputValue(),content);assert.equal(await page.evaluate(()=>GAReaderComposer.editor.request_key),key);assert.deepEqual(await page.evaluate(()=>GAReaderComposer.editor.source),source);
  await page.locator('#annotation-save').click();await page.waitForFunction(()=>GAReaderComposer.editor===null);await wait(400);assert.equal((await api('annotations/')).data.count,before+1);assert.equal(await page.locator('#annotation-overview').isVisible(),false);assert.equal(await page.locator('#annotation-rail .annotation-card:visible,#inline-thread .annotation-card:visible').count(),1);
  const notes=(await api('annotations/')).data.threads;global.ownNote=notes.find(n=>n.body===content);assert.ok(global.ownNote);global.savedSource=source;
  const retry=await api('annotations/','POST',{body:content,source,request_key:key});assert.equal(retry.status,200);assert.equal(retry.data.id,global.ownNote.id);await shot('inline-same-source');
  await newDraft('不提交的草稿');const count=(await api('annotations/')).data.count;await page.locator('#annotation-discard').click();await page.locator('#discard-yes').click();assert.equal((await api('annotations/')).data.count,count);
 });
 await check('A4 E2 keyed polling focus, replies and real 409 reconciliation',async()=>{
  assert.ok(global.ownNote);await page.evaluate(id=>GAReaderAnnotations.locate(GAReaderAnnotations.notes.get(id)),global.ownNote.id);await wait(200);
  const card=page.locator(`.annotation-card[data-thread="${global.ownNote.id}"]:visible`);await card.locator('[data-action=reply]').click();await page.locator('#annotation-body').fill('v3 回复 '+Date.now());await page.locator('#annotation-save').click();await page.waitForFunction(()=>!GAReaderComposer.visible);await wait(220);await card.locator('.annotation-replies summary').click();
  await card.locator('[data-action=reply]').focus();await page.evaluate(id=>{window.__cardBefore=document.querySelector(`.annotation-card[data-thread="${id}"]`);},global.ownNote.id);await page.evaluate(()=>GAReaderAnnotations.refresh());assert.equal(await page.evaluate(id=>window.__cardBefore===document.querySelector(`.annotation-card[data-thread="${id}"]`),global.ownNote.id),true);assert.equal(await card.locator('.annotation-replies').getAttribute('open'),'');assert.equal(await card.locator('[data-action=reply]').evaluate(el=>el===document.activeElement),true);
  await card.locator(`[data-action=edit-${global.ownNote.id}]`).click();await page.locator('#annotation-body').fill('v3 保留的冲突草稿');const latest=(await api('annotations/')).data.threads.find(n=>n.id===global.ownNote.id);assert.equal((await api(`comments/${latest.id}/`,'PATCH',{body:'另一标签页已修改',version:latest.version})).status,200);
  await page.locator('#annotation-save').click();await page.locator('#annotation-conflict').waitFor({state:'visible'});assert.equal(await page.locator('#annotation-body').inputValue(),'v3 保留的冲突草稿');await page.locator('#annotation-conflict').click();await page.locator('#conflict-apply').waitFor({state:'visible'});assert.equal(await page.locator('#conflict-content').textContent(),'另一标签页已修改');await page.locator('#conflict-apply').click();await page.locator('#annotation-save').click();await page.waitForFunction(()=>!GAReaderComposer.visible);assert.equal(await page.locator('#annotation-overview').isVisible(),false);
  await card.locator('[data-action=reply]').click();await page.locator('#annotation-body').fill('轮询期间的中文草稿');await page.locator('#annotation-body').focus();await wait(26000);assert.equal(await page.locator('#annotation-body').inputValue(),'轮询期间的中文草稿');assert.equal(await page.locator('#annotation-body').evaluate(el=>el===document.activeElement),true);assert.equal(await page.locator('#annotation-overview').isVisible(),false);await page.locator('#annotation-discard').click();await page.locator('#discard-yes').click();
 });
 await check('A4 A6 duplicated tab drafts have independent ownership',async()=>{
  await newDraft('主标签页草稿');const key1=await page.evaluate(()=>GAReaderComposer.editor.key);
  const opened=context.waitForEvent('page');await page.evaluate(()=>window.open(location.href,'_blank'));const sibling=await opened;await sibling.waitForLoadState('load');await sibling.waitForTimeout(350);assert.equal(await sibling.locator('#continue-draft').isVisible(),false);
  await sibling.evaluate(source=>GAReaderComposer.open({source}),global.savedSource);await sibling.locator('#annotation-body').fill('另一个标签页草稿');const key2=await sibling.evaluate(()=>GAReaderComposer.editor.key);assert.notEqual(key1,key2);assert.equal(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)).body,key1),'主标签页草稿');await sibling.close();await page.locator('#annotation-discard').click();await page.locator('#discard-yes').click();
 });
 await check('B2 B3 B4 B5 cross representation semantics and real connector endpoint',async()=>{
  await page.locator('button[data-view=both]').click();await page.evaluate(id=>GAReaderAnnotations.locate(GAReaderAnnotations.notes.get(id)),global.ownNote.id);await wait(300);assert.equal(await page.locator(`.annotation-card[data-thread="${global.ownNote.id}"]:visible`).getAttribute('data-relationship'),'direct');
  await page.locator('button[data-view=zh]').click();await page.evaluate(()=>GAReaderAnnotations.refresh({full:true}));await page.evaluate(id=>GAReaderAnnotations.locate(GAReaderAnnotations.notes.get(id)),global.ownNote.id);await wait(200);assert.equal(await page.locator(`.annotation-card[data-thread="${global.ownNote.id}"]:visible`).getAttribute('data-relationship'),'direct');
  for(const size of [12,18,32,40]){await page.locator('#font-size').fill(String(size));await page.locator('#font-size').dispatchEvent('change');await page.evaluate(id=>GAReaderAnnotations.locate(GAReaderAnnotations.notes.get(id)),global.ownNote.id);await wait(250);const geometry=await page.evaluate(id=>{GAReaderAnnotations.paintGeometry();const n=GAReaderAnnotations.notes.get(id),r=n.projections.flatMap(GAReaderGeometry.rectsFor).filter(r=>r.bottom>document.querySelector('.readerbar').getBoundingClientRect().bottom&&r.top<innerHeight).at(-1),line=document.querySelector(`#annotation-connectors path[data-thread="${id}"]`);return {range:!!r,line:line?{x:+line.dataset.sourceX,y:+line.dataset.sourceY}:null,expected:r?{x:r.right,y:r.bottom+2}:null,rail:document.querySelector('#reading-layout').classList.contains('with-rail')};},global.ownNote.id);assert.ok(geometry.range);if(geometry.rail){assert.ok(geometry.line,JSON.stringify(geometry));assert.ok(Math.abs(geometry.line.x-geometry.expected.x)<2);assert.ok(Math.abs(geometry.line.y-geometry.expected.y)<2);}}
  await page.locator('#font-reset').click();await page.locator('button[data-view=en]').click();await page.evaluate(()=>GAReaderAnnotations.refresh({full:true}));await page.evaluate(id=>GAReaderAnnotations.locate(GAReaderAnnotations.notes.get(id)),global.ownNote.id);await wait(250);const foreign=page.locator(`.annotation-card[data-thread="${global.ownNote.id}"]:visible`);assert.equal(await foreign.getAttribute('data-relationship'),'cross');assert.match(await foreign.textContent(),/来自中文版本的批注/);assert.equal(await foreign.getAttribute('data-precision'),'block');await shot('inline-foreign-source');
 });
 await check('C1 C2 A5 direct source visit, logical return, browser history and inline-off',async()=>{
  const position=await page.evaluate(()=>GAReader.capturePosition());const sourceButton=page.locator(`.annotation-card[data-thread="${global.ownNote.id}"]:visible [data-action=source-0]`);await sourceButton.click();await page.waitForFunction(()=>GAReader.view==='zh');await page.locator('#source-return').waitFor({state:'visible'});await wait(300);assert.equal(await page.locator('#annotation-overview').isVisible(),false);assert.match(page.url(),/thread=/);assert.ok(!page.url().includes('return='));await shot('source-return');await page.locator('#source-return').click();await page.waitForFunction(()=>GAReader.view==='en'&&!GAReaderNavigation.busy);await wait(200);const after=await page.evaluate(()=>GAReader.capturePosition());assert.equal(after.unit_id,position.unit_id,JSON.stringify({position,after}));assert.ok(Math.abs(after.offset-position.offset)<8,JSON.stringify({position,after}));
  await page.goBack();await page.waitForFunction(()=>GAReader.view==='zh');await page.goForward();await page.waitForFunction(()=>GAReader.view==='en');
  await page.locator('#inline-toggle').click();await page.evaluate(()=>GAReaderAnnotations.paintGeometry());assert.equal(await page.locator('#annotation-connectors path').count(),0);assert.equal(await page.locator('#annotation-markers button').count(),0);assert.equal(await page.locator('#reading-layout').evaluate(el=>el.classList.contains('with-rail')),false);
  await page.locator('#annotations-toggle').click();await page.locator(`#annotation-list .annotation-card[data-thread="${global.ownNote.id}"] [data-action=source-0]`).click();await page.waitForFunction(()=>GAReader.view==='zh');await page.locator('#focus-clear').waitFor({state:'visible'});assert.equal(await page.evaluate(()=>GAReader.settings.inline),false);assert.equal(await page.locator('#annotation-overview').isVisible(),false);await page.locator('#focus-clear').click();await page.evaluate(()=>GAReaderAnnotations.paintGeometry());assert.equal(await page.locator('#annotation-connectors path').count(),0);await page.locator('#inline-toggle').click();
 });
 await check('B6 twenty overlapping threads collapse to accessible picker without empty tail',async()=>{
  await read();await page.locator('#font-reset').click();await select();const source=await page.evaluate(()=>GAReaderAnnotations.selection.source);const ids=[];for(let i=0;i<20;i++){const r=await api('annotations/','POST',{body:`v3 密集批注 ${i+1}`,source,request_key:require('crypto').randomUUID()});assert.equal(r.status,201);ids.push(r.data.id);}global.denseIds=ids;await page.evaluate(()=>GAReaderAnnotations.refresh({full:true}));await page.evaluate(id=>GAReaderAnnotations.locate(GAReaderAnnotations.notes.get(id)),ids[0]);await wait(300);assert.ok(await page.locator('#annotation-rail .annotation-card:visible,#inline-thread .annotation-card:visible').count()<=2);const marker=page.locator('.annotation-marker').filter({hasText:/2[0-9]/}).first();await marker.focus();await page.keyboard.press('Enter');await page.locator('#annotation-picker').waitFor({state:'visible'});assert.ok(await page.locator('#annotation-picker button').count()>=20);await page.keyboard.press('Tab');await page.keyboard.press('Enter');assert.equal(await page.locator('#annotation-picker').isVisible(),false);assert.equal(await page.locator('#annotation-rail').evaluate(el=>el.offsetHeight),0);await shot('dense-twenty');
 });
 await check('B7 C3 PDF multi-segment, transforms, exact versus HTML and async cancellation',async()=>{
  await read(ammonia,'pdf');await page.waitForFunction(()=>GAReaderPDF?.pages.get(0)?.textLayer);await page.evaluate(()=>GAReaderAnnotations.refresh({full:true}));const cross=await page.evaluate(()=>[...GAReaderAnnotations.notes.values()].find(n=>n.source?.created_view==='pdf'&&n.source.segments.length===2));assert.ok(cross);global.pdfCross=cross;
  await page.evaluate(id=>GAReaderAnnotations.locate(GAReaderAnnotations.notes.get(id),{segment:1}),cross.id);await wait(300);await page.locator('#annotations-toggle').click();const card=page.locator(`#annotation-list .annotation-card[data-thread="${cross.id}"]`);await card.locator('summary').first().click();assert.equal(await card.locator('.source-object').count(),2);assert.match(await card.locator('.source-object').nth(0).textContent(),/文件第 1 页/);assert.match(await card.locator('.source-object').nth(1).textContent(),/文件第 2 页/);await card.locator('.source-object').nth(0).click();await page.waitForFunction(()=>GAReaderPDF.currentPage()===0&&!GAReaderNavigation.busy&&document.getElementById('annotation-overview').hidden);await page.locator('#annotations-toggle').click();await page.locator(`#annotation-list .annotation-card[data-thread="${cross.id}"] [data-action=source-1]`).click();await page.waitForFunction(()=>GAReaderPDF.currentPage()===1&&!GAReaderNavigation.busy&&document.getElementById('annotation-overview').hidden);assert.equal(await page.locator('#annotation-overview').isVisible(),false);
  const cases=[];for(const zoom of [50,100,300])for(let rotate=0;rotate<4;rotate++){await page.locator('#pdf-scale').fill(String(zoom));await page.locator('#pdf-scale').dispatchEvent('change');if(rotate)await page.locator('#pdf-rotate').click();await page.evaluate(id=>GAReaderAnnotations.locate(GAReaderAnnotations.notes.get(id),{segment:1}),cross.id);await wait(300);const result=await page.evaluate(id=>{const n=GAReaderAnnotations.notes.get(id),p=n.projections.find(p=>p.page_index===1),info=GAReaderPDF.pages.get(1),rect=GAReaderPDF.projectedRects(p)[0],bounds=info.surface.getBoundingClientRect(),xy=info.viewport.convertToViewportPoint(p.quads[0][0],p.quads[0][1]);return {page:GAReaderPDF.currentPage(),rect:!!rect,view:GAReader.view,rotation:GAReaderPDF.rotation,pages:[...new Set(n.projections.map(p=>p.page_index))],finite:Number.isFinite(xy[0]+xy[1]),overflow:document.documentElement.scrollWidth<=innerWidth+2};},cross.id);assert.equal(result.page,1);assert.ok(result.rect&&result.finite&&result.overflow);assert.deepEqual(result.pages,[0,1]);cases.push({zoom,rotation:result.rotation});}await shot('pdf-crosspage');
  await page.locator('button[data-view=en]').click();await page.evaluate(()=>GAReaderAnnotations.refresh({full:true}));assert.equal(await page.evaluate(n=>GAAnnotationPresentation.relation(n.source,{revision:GAReader.reader.dataset.revision,view:'en',units:new Set(),representations:new Set()}),cross),'cross');
  await page.route('**/pdf/',async route=>{await wait(800);await route.continue();});await page.reload();await page.waitForFunction(()=>GAReaderAnnotations?.notes.size>0);await page.locator('button[data-view=pdf]').click();await page.locator('button[data-view=zh]').click();await wait(1800);assert.equal(await page.locator('#reader').getAttribute('data-view'),'zh');await page.unroute('**/pdf/');return {transforms:cases};
 });
 await check('B8 mobile one-editor interaction and no automatic overview',async()=>{await page.setViewportSize({width:390,height:844});await read();await page.locator('#font-reset').click();await newDraft('手机阅读的单条草稿');assert.equal(await page.locator('#annotation-overview').isVisible(),false);const size=await page.locator('#annotation-composer').boundingBox();assert.ok(size.x>=0&&size.x+size.width<=390&&size.y>=0&&size.y+size.height<=844);await shot('mobile-compose');await page.locator('#composer-close').click();await page.locator('#continue-draft').click();assert.equal(await page.locator('#annotation-body').inputValue(),'手机阅读的单条草稿');await page.locator('#annotation-discard').click();await page.locator('#discard-yes').click();});

 if(!process.env.GA_SKIP_MATRIX) await check('E4 real HTML viewport/theme/font matrix',async()=>{const cases=[];for(const paper of [idaes,ammonia]){await read(paper);for(const [width,height] of [[1366,768],[1440,900],[1920,1080],[390,844]]){await page.setViewportSize({width,height});for(const theme of ['light','dark'])for(const font of [12,18,32,40]){await page.locator('#theme').selectOption(theme);await page.locator('#font-size').fill(String(font));await page.locator('#font-size').dispatchEvent('change');for(const view of ['both','zh','en']){await page.locator(`button[data-view=${view}]`).click();await wait(90);const metrics=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,bar:document.querySelector('.readerbar').getBoundingClientRect().height,font:getComputedStyle(document.querySelector('#article')).fontSize}));assert.ok(metrics.scroll<=metrics.width+2,JSON.stringify({paper:paper.profile,width,height,theme,font,view,metrics}));assert.equal(metrics.font,font+'px');cases.push({paper:paper.profile,width,height,theme,font,view});}}} }await shot('large-font-40');return {cases:cases.length};});
 await check('E5 reduced motion system/application and server rendered home',async()=>{await page.goto(base+'/');await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.home-sections').evaluate(el=>getComputedStyle(el).animationName),'none');await page.emulateMedia({reducedMotion:'no-preference'});await page.locator('#reduce-motion').check();assert.equal(await page.locator('.home-sections').evaluate(el=>getComputedStyle(el).animationName),'none');await shot('reduced-motion');const nojs=await browser.newContext({javaScriptEnabled:false,storageState:await context.storageState()});const p=await nojs.newPage();await p.goto(base+'/');assert.equal(await p.locator('#recent .paper-row').count(),2);assert.ok(await p.locator('.home-section').count()>1);await nojs.close();});
 await browser.close();report.errors=[...new Set(report.errors)];fs.writeFileSync(path.join(output,'browser-results.json'),JSON.stringify(report,null,2));if(report.checks.some(c=>c.status==='FAIL')||report.errors.length)process.exitCode=1;
}
main().catch(async e=>{console.error(e);if(browser)await browser.close();process.exitCode=1;});
